import {
    enable,
    run,
} from './content';
import * as popup from './popup';
import * as background from './background';

export const _description = 'This object is generated by the TeX to Unicode extension.';

export {
    background,
    popup,
    enable,
    run,
};
